import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider"
import "./globals.css";
import LeftBar from "@/components/Left/LeftBar";
import RightBar from "@/components/Right/RightBar";
import SessionProvider from "@/components/SessionProvider";
import { Toaster } from "@/components/ui/toaster";
import Sleft from "@/components/Sleft/Sleft";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "eDi9root personal blog",
  description: "Generated by Junseok Oh, @eDi9root",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <main>
              <div className="max-w-[100rem] mx-auto">
                  <div className="hidden w-full mt-4 mb-[-20px] max-md:flex justify-center">
                    <Sleft />
                  </div>
                <div className="gap-10 flex md:mt-5 flex-col md:flex-row">

                  {children}
                  <RightBar />
                </div>
              </div>              
            </main>
            <Toaster />
            
          </ThemeProvider>
          <SessionProvider />
      </body>
    </html>
  );
}
